### ISSUE TITLE
TypeError: Unexpected keyword argument passed to optimizer: learning_rate

### ISSUE THREAD

**Issue by mdehollander** [leylabmpi/DeepMAsED#2]
After reading the preprint I am giving DeepMAsED a try, but are getting this error when using the test data:

```
(deepmased-env) user@server:~/src/DeepMAsED$ DeepMAsED predict --cpu-only ./tests/data/n1000_r3/map/2/megahit/features.tsv.gz tests/data/n1000_r3/model
Using TensorFlow backend.
/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2019-10-18 17:34:52,121 - Setting env for CPU-only mode...
2019-10-18 17:34:52,121 - Loading model...
2019-10-18 17:34:52.192605: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/keras/utils/conv_utils.py:82: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.copy(kernel[slices])
Traceback (most recent call last):
  File "/home/user/.conda/envs/deepmased-env/bin/DeepMAsED", line 11, in <module>
    load_entry_point('DeepMAsED==0.2.1', 'console_scripts', 'DeepMAsED')()
  File "/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/DeepMAsED-0.2.1-py3.6.egg/DeepMAsED/__main__.py", line 53, in main
    args.func(args)
  File "/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/DeepMAsED-0.2.1-py3.6.egg/DeepMAsED/Commands/Predict.py", line 54, in main
    Predict.main(args)
  File "/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/DeepMAsED-0.2.1-py3.6.egg/DeepMAsED/Predict.py", line 48, in main
    model = load_model(F, custom_objects=custom_obj)
  File "/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/keras/engine/saving.py", line 299, in _deserialize_model
    custom_objects=custom_objects)
  File "/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/keras/optimizers.py", line 768, in deserialize
    printable_module_name='optimizer')
  File "/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/keras/optimizers.py", line 154, in from_config
    return cls(**config)
  File "/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/keras/optimizers.py", line 460, in __init__
    super(Adam, self).__init__(**kwargs)
  File "/home/user/.conda/envs/deepmased-env/lib/python3.6/site-packages/keras/optimizers.py", line 79, in __init__
    'passed to optimizer: ' + str(k))
TypeError: Unexpected keyword argument passed to optimizer: learning_rate
```

Am I running it in the correct way? A bit more detailed tutorial would be welcome.

**Comment by nick-youngblut** [comment]
Sorry for the slow response. What's your conda env? Make sure your conda env setup matches the `conda create` section in the `.travis.yaml` file. 

In regards to a tutorial, that's in progress. The `data-path` arg should be pointing to the parent directory that contains all of the feature tables. In your case, the command should be `DeepMAsED predict --cpu-only ./tests/data/n1000_r3/map/ tests/data/n1000_r3/model`

**Comment by nick-youngblut** [comment]
The code has been changed quite a lot since Oct 2019. Please try again and let me know if you still have problems.

**Comment by cjkumar** [comment]
I am stillk getting the error,
 TypeError: Unexpected keyword argument passed to optimizer: learning_rate

**Comment by nick-youngblut** [comment]
That's with the latest version? Can you please send the command that you used (the one listed above shouldn't work with the updated UI)? Also, please list your conda environment
