### ISSUE TITLE
compute_predictions: AttributeError: 'list' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by chrisLanderson** [leylabmpi/DeepMAsED#5]
Hello,

I tried to predict misassemblies after successfully generating the features table (DeepMAsED features bam_fasta_table). However, the below error is quickly generated when running the compute_predictions function. It appears a numpy array was expected and the input was a list instead?

Thanks for your hard work on this very useful project!

**Command (Running on a GPU with tensorflow-gpu==2.0; cloned after the latest commit in the DeepMAsED repo):**
DeepMAsED predict feature_file_table.tsv

**All output to stderr for context:**
Using TensorFlow backend.
2020-04-08 13:16:26,729 - Loading model...
2020-04-08 13:16:26,731 -   Loading mstd...
2020-04-08 13:16:26,751 -   Loading h5...
2020-04-08 13:16:26.836078: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-08 13:16:26.875078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla K40m major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:0b:00.0
2020-04-08 13:16:26.880811: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-08 13:16:26.911417: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-08 13:16:26.931989: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-04-08 13:16:26.949929: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-04-08 13:16:26.980828: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-04-08 13:16:26.998555: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-04-08 13:16:27.542094: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-08 13:16:27.545073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-04-08 13:16:27.545987: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-08 13:16:27.562228: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600165000 Hz
2020-04-08 13:16:27.562628: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d786ccf160 executing computations on platform Host. Devices:
2020-04-08 13:16:27.562686: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-04-08 13:16:27.772092: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d786cd1c20 executing computations on platform CUDA. Devices:
2020-04-08 13:16:27.772174: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla K40m, Compute Capability 3.5
2020-04-08 13:16:27.773155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla K40m major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:0b:00.0
2020-04-08 13:16:27.773231: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-08 13:16:27.773268: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-08 13:16:27.773298: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-04-08 13:16:27.773327: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-04-08 13:16:27.773357: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-04-08 13:16:27.773387: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-04-08 13:16:27.773416: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-08 13:16:27.774692: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-04-08 13:16:27.774780: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-08 13:16:27.781448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-08 13:16:27.781487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-04-08 13:16:27.781506: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-04-08 13:16:27.783206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10794 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:0b:00.0, compute capability: 3.5)
2020-04-08 13:16:38,490 - Loading features...
2020-04-08 13:16:38,496 - Input file exists: /scratch/vosloo.s/BostonTap/timeseries_data/03_assembly/07_deepmased/test.spades.C01/C01.spades.sorted_feats.tsv
2020-04-08 13:16:38,496 -   --force-overwrite=False; searching for pkl version of tsv file
2020-04-08 13:16:38,496 -   No pkl found. A pkl file will be created from the tsv file
#-- Feature file table summary --#
Assembler = NA; File type = tsv; No. of files: 1
#--------------------------------#
2020-04-08 13:16:38,496 - Pickling...
2020-04-08 13:16:38,516 - Pickling feature data: /scratch/vosloo.s/BostonTap/timeseries_data/03_assembly/07_deepmased/test.spades.C01/C01.spades.sorted_feats.tsv => /scratch/vosloo.s/BostonTap/timeseries_data/03_assembly/07_deepmased/test.spades.C01/features.pkl
2020-04-08 13:16:39,096 -   Dumping pickle file
2020-04-08 13:16:39,124 - Loading file: /scratch/vosloo.s/BostonTap/timeseries_data/03_assembly/07_deepmased/test.spades.C01/features.pkl
2020-04-08 13:16:39,126 - Contigs filtered due to low coverage: 14
2020-04-08 13:16:39,126 - Loaded 45 contigs
2020-04-08 13:16:39,126 - Running model generator...
2020-04-08 13:16:39,126 - Computing predictions...
Traceback (most recent call last):
  File "/scratch/vosloo.s/software/miniconda3/envs/DeepMAsED/bin/DeepMAsED", line 11, in <module>
    load_entry_point('DeepMAsED==0.3.0', 'console_scripts', 'DeepMAsED')()
  File "/scratch/vosloo.s/software/miniconda3/envs/DeepMAsED/lib/python3.6/site-packages/DeepMAsED-0.3.0-py3.6.egg/DeepMAsED/__main__.py", line 57, in main
    args.func(args)
  File "/scratch/vosloo.s/software/miniconda3/envs/DeepMAsED/lib/python3.6/site-packages/DeepMAsED-0.3.0-py3.6.egg/DeepMAsED/Commands/Predict.py", line 76, in main
    Predict.main(args)
  File "/scratch/vosloo.s/software/miniconda3/envs/DeepMAsED/lib/python3.6/site-packages/DeepMAsED-0.3.0-py3.6.egg/DeepMAsED/Predict.py", line 73, in main
    args.save_path, args.save_name)
  File "/scratch/vosloo.s/software/miniconda3/envs/DeepMAsED/lib/python3.6/site-packages/DeepMAsED-0.3.0-py3.6.egg/DeepMAsED/Utils.py", line 599, in compute_predictions
    score_val = score_val.flatten()
AttributeError: 'list' object has no attribute 'flatten'

**Comment by nick-youngblut** [comment]
@chrisLanderson the issue was caused by the fact that your number of contigs was less than the batch size, and the code had a bug causing it to error out in such a scenario. It should be fixed now. Please close the issue if it is or let us know if you are still running into issues.

**Comment by chrisLanderson** [comment]
Ah that makes sense. This was an assembly from a negative control that we were testing. Thanks!
