### ISSUE TITLE
failed to load bam file

### ISSUE THREAD

**Issue by jtamames** [leylabmpi/DeepMAsED#6]
Hello!
DeepMAsED fails to load the .bam file, even if it is present. This is my bam_fasta table:
```
bam	fasta
nosingletons_flye.singletons.bam	01.nosingletons_flye.fasta

```
When running DeepMAsED, I get:

```
2020-07-08 14:55:08,556 - Indexing file: 01.nosingletons_flye.fasta
2020-07-08 14:55:14,015 - Cannot find nosingletons_flye.singletons.bam.bai; creating...

[E::hts_idx_push] NO_COOR reads not in a single block at the end 915 -1
samtools index: failed to create index for "nosingletons_flye.singletons.bam": No such file or directory

```
So it is able to find and index the fasta file, but not the sam file. What am I doing wrong?
Best,
Javier

**Comment by nick-youngblut** [comment]
Are you able to create an index on the bam file with samtools on your own? It seems like something is wrong with the bam file.

**Comment by jtamames** [comment]
Hello @nick-youngblut, thanks for your quick response.

Yes, I was able to index the file. Still I got the same error.

This is my directory:
```
-rw-r--r-- 1 tamames javier 1691690199 jul  8 14:26 01.nosingletons_flye.fasta
-rw-r--r-- 1 tamames javier 6373134713 jul  8 14:28 nosingletons_flye.singletons.sam
-rw-r--r-- 1 tamames javier 3301501328 jul  8 14:37 nosingletons_flye.singletons.bam
-rw-r--r-- 1 tamames javier         70 jul  8 14:55 bam_fasta.table
-rw-r--r-- 1 tamames javier  407229940 jul  8 16:26 samtools.6153.7024.tmp.0000.bam
-rw-r--r-- 1 tamames javier 3259019114 jul  8 16:32 nosingletons_flye.singletons.sorted.bam
-rw-r--r-- 1 tamames javier     403000 jul  8 16:39 nosingletons_flye.singletons.sorted.bam.bai
-rw-r--r-- 1 tamames javier   34227339 jul  8 16:39 01.nosingletons_flye.fasta.fai

```

Best,
Javier

**Comment by nick-youngblut** [comment]
Can you please post the entire error message and the command used to generate it?

**Comment by jtamames** [comment]
Here it is:
```
(deepmased) tamames@rigaud:~/test$ DeepMAsED features bam_fasta.table
2020-07-08 16:39:40,408 - Indexing file: 01.nosingletons_flye.fasta
2020-07-08 16:39:45,759 - Cannot find nosingletons_flye.singletons.bam.bai; creating...

[E::hts_idx_push] NO_COOR reads not in a single block at the end 915 -1
samtools index: failed to create index for "nosingletons_flye.singletons.bam": No such file or directory

Traceback (most recent call last):
  File "/home/tamames/soft/anaconda2/envs/deepmased/bin/DeepMAsED", line 10, in <module>
    sys.exit(main())
  File "/home/tamames/soft/anaconda2/envs/deepmased/lib/python3.6/site-packages/DeepMAsED/__main__.py", line 57, in main
    args.func(args)
  File "/home/tamames/soft/anaconda2/envs/deepmased/lib/python3.6/site-packages/DeepMAsED/Commands/Features.py", line 69, in main
    Features.main(args)
  File "/home/tamames/soft/anaconda2/envs/deepmased/lib/python3.6/site-packages/DeepMAsED/Features.py", line 240, in main
    index_bam(bam_file, threads=args.procs)
  File "/home/tamames/soft/anaconda2/envs/deepmased/lib/python3.6/site-packages/DeepMAsED/Features.py", line 195, in index_bam
    raise IOError('samtools return code: {}'.format(rc))
OSError: samtools return code: 1

```

**Comment by jtamames** [comment]
But, I cannot index the unsorted bam file with samtools:
```
(deepmased) tamames@rigaud:~/test$ samtools index nosingletons_flye.singletons.bam
[E::hts_idx_push] NO_COOR reads not in a single block at the end 915 -1
samtools index: failed to create index for "nosingletons_flye.singletons.bam": No such file or directory

```

**Comment by jtamames** [comment]
And now, providing the sorted.bam file in the bam_fasta table, it is working

**Comment by nick-youngblut** [comment]
Thanks for the details! I thought that you were able to index the bam file: 

> Yes, I was able to index the file. Still I got the same error.

**Comment by nick-youngblut** [comment]
Yeah, it seems that something is wrong with your bam file. It might be helpful to convert your bam file to a sam file and inspect it.

**Comment by jtamames** [comment]
Well, it is working when I sorted it first. I guess I needed to do that, right?

**Comment by nick-youngblut** [comment]
Yes you do. I should make that clear in the docs

**Comment by jtamames** [comment]
Thank you @nick-youngblut
